# Generated by Django 4.0.4 on 2022-07-19 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_speaker_user_alter_meetup_meetup_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetup',
            name='location_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetup',
            name='location_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
