# Generated by Django 4.0.4 on 2022-07-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_location_user_meetup_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='meetup_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
