# Generated by Django 4.0.4 on 2022-07-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_speaker_email_speaker_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meetup',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default='2022-07-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='meetup_date',
            field=models.DateField(default='2022-07-20'),
            preserve_default=False,
        ),
    ]
