# Generated by Django 4.0.4 on 2022-07-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_meetup_activate_meetup_create_meetup_meetup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='from_date',
            field=models.DateField(default='2022-07-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='meetup_time',
            field=models.DateTimeField(default='2022-08-22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='to_date',
            field=models.DateField(default='2022-09-12'),
            preserve_default=False,
        ),
    ]
