# Generated by Django 4.0.4 on 2022-12-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0010_alter_meetup_meetup_date_alter_meetup_meetup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
